Artifacts:
- SourceArtifact: dp.apps.rancher.io/containers/clamav
  Tags:
  - 1.4.4-11.2
  - 1.4.5-11.5
Repositories:
- BaseUrl: docker.io/rancher
  DefaultTarget: true
  Password: '{{ env "DOCKER_PASSWORD" }}'
  Registry: docker.io
  RepoAuth: true
  Username: '{{ env "DOCKER_USERNAME" }}'
- BaseUrl: dp.apps.rancher.io/charts
  DefaultTarget: false
  Password: '{{ env "APPCO_PASSWORD" }}'
  Registry: dp.apps.rancher.io
  Username: '{{ env "APPCO_USERNAME" }}'
- BaseUrl: dp.apps.rancher.io/containers
  DefaultTarget: false
  Password: '{{ env "APPCO_PASSWORD" }}'
  Registry: dp.apps.rancher.io
  Username: '{{ env "APPCO_USERNAME" }}'
- BaseUrl: registry.suse.com/rancher
  DefaultTarget: true
  Password: '{{ env "PRIME_PASSWORD" }}'
  Registry: registry.suse.com
  RepoAuth: true
  Username: '{{ env "PRIME_USERNAME" }}'
- BaseUrl: registry.suse.com/rancher/charts
  DefaultTarget: false
  Password: '{{ env "PRIME_PASSWORD" }}'
  Registry: registry.suse.com
  RepoAuth: true
  Username: '{{ env "PRIME_USERNAME" }}'
- BaseUrl: stgregistry.suse.com/rancher
  DefaultTarget: true
  Password: '{{ env "PRIME_STAGING_PASSWORD" }}'
  Registry: stgregistry.suse.com
  RepoAuth: true
  Username: '{{ env "PRIME_STAGING_USERNAME" }}'
- BaseUrl: stgregistry.suse.com/rancher/charts
  DefaultTarget: false
  Password: '{{ env "PRIME_STAGING_PASSWORD" }}'
  Registry: stgregistry.suse.com
  RepoAuth: true
  Username: '{{ env "PRIME_STAGING_USERNAME" }}'
