name: Pull request checks

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.27'

      - name: Run unit tests
        run: |
          cd tools
          go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.27'

      - name: Run linter
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          working-directory: tools
          args: --timeout=5m

  formatting-is-valid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.27'

      - name: Ensure that files are formatted correctly
        run: |
          scripts/build-tools.sh
          bin/artifact-mirror-tools format
          # fail if there are changes in the working tree
          git diff --exit-code

  regsync-yaml-synced:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.27'

      - name: Ensure that regsync.yaml is in sync with config.yaml
        run: |
          scripts/build-tools.sh
          bin/artifact-mirror-tools generate-regsync
          # fail if there are changes in the working tree
          git diff --exit-code

  run-validate-subcommand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: '1.27'

      - name: Run bin/artifact-mirror-tools validate
        run: |
          scripts/build-tools.sh
          bin/artifact-mirror-tools validate --merge-base-branch origin/master
